Console.WriteLine("введите день недели ");
string entry = Console.ReadLine();
if(entry.ToLower()=="понедельник")
{
    Console.WriteLine("1");
}
if(entry.ToLower()=="вторник")
{
    Console.WriteLine("2");
}
if(entry.ToLower()=="среда")
{
    Console.WriteLine("3");
}
if(entry.ToLower()=="четверг")
{
    Console.WriteLine("4");
}
if(entry.ToLower()=="пятница")
{
    Console.WriteLine("5");
}
if(entry.ToLower()=="суббота")
{
    Console.WriteLine("6");
}
if(entry.ToLower()=="воскресенье")
{
    Console.WriteLine("7");
}